# Generated by Django 2.1.7 on 2020-09-08 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.TextField(max_length=255, null=True)),
                ('cases', models.BigIntegerField(null=True)),
                ('todayCases', models.BigIntegerField(null=True)),
                ('deaths', models.BigIntegerField(null=True)),
                ('todayDeaths', models.BigIntegerField(null=True)),
                ('recovered', models.BigIntegerField(null=True)),
                ('active', models.BigIntegerField(null=True)),
                ('critical', models.BigIntegerField(null=True)),
                ('casesPerOneMillion', models.BigIntegerField(null=True)),
                ('deathsPerOneMillion', models.BigIntegerField(null=True)),
                ('totalTests', models.BigIntegerField(null=True)),
                ('testsPerOneMillion', models.BigIntegerField(null=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
